### ISSUE TITLE
Rest

### ISSUE THREAD

**Issue by Szymon-Krysztopolski** [Gacioreks/ScenarioQualityChecker#11]

**Comment by Szymon-Krysztopolski** [comment]
Jako twórca narzędzi dla analityków mogę korzystać z dostępnych funkcji zdalnie poprzez REST, aby móc  zintegrować narzędzie z moimi innymi aplikacjami

**Comment by Szymon-Krysztopolski** [comment]
niby wszystko działa, ALE 
rzuca wyjątkami dość widowiskowo 
póki działa to na spokojnie, można zająć się tym później

**Comment by iti-tobiasz-gruszczynski** [comment]
Sprawdzone i przetestowane metody restowe
