### ISSUE TITLE
Dokumentacja 

### ISSUE THREAD

**Issue by Grabosk1** [Gacioreks/ScenarioQualityChecker#12]

**Comment by Grabosk1** [comment]
Dokumentacja generuje się w sposób automatyczny podczas budowy oprogramowania

**Comment by Grabosk1** [comment]
Przynajmniej 1 klasa / interfejs posiada pełną dokumentację techniczną* (javadoc, itp.)

**Comment by iti-tobiasz-gruszczynski** [comment]
Wstępne założenie wykonanie dla przynajmniej 3 klas

**Comment by Grabosk1** [comment]
Pierwsza Klasa Done

**Comment by Grabosk1** [comment]
Dodano pozostałe dwie klasy dokumentacji.
