### ISSUE TITLE
Zadanie - ile słów kluczy

### ISSUE THREAD

**Issue by Szymon-Krysztopolski** [Gacioreks/ScenarioQualityChecker#14]
Jako analityk mogę sprawdzić ile kroków zawiera słowa kluczowe, aby dowiedzieć się jak wiele decyzji warunkowych znajduje się w scenariuszu

**Comment by Gacioreks** [comment]
Zaimplementowane zgodnie z wzorcem Wizytator za pomocą KeyWordVisitor
