### ISSUE TITLE
Zadanie - numeracja

### ISSUE THREAD

**Issue by Szymon-Krysztopolski** [Gacioreks/ScenarioQualityChecker#16]
Jako analityk mogę pobrać scenariusz w postaci tekstu z numeracją kroków, aby móc włączyć go do dokumentacji

**Comment by iti-tobiasz-gruszczynski** [comment]
Małe problemy przy kolejnych podscenariuszach

**Comment by Grabosk1** [comment]
Numeracja Scenariusza oraz PodScenariusza działa zgodnie z wymaganiami
