### ISSUE TITLE
Zadania - pod scenariusze do określonego poziomu

### ISSUE THREAD

**Issue by Szymon-Krysztopolski** [Gacioreks/ScenarioQualityChecker#17]
Jako analityk mogę uzyskać scenariusz zawierający pod-scenariusze tylko do określonego poziomu, aby zaprezentować uproszczoną wersję wymagań

**Comment by iti-tobiasz-gruszczynski** [comment]
Zadanko wykonane. Trzeba przedyskutować czy pierwszy stopień traktujemy jako 0 czy jako 1

**Comment by Szymon-Krysztopolski** [comment]
imo 0 bo bardziej naturalne

**Comment by Szymon-Krysztopolski** [comment]
ale wiadomo, masz klient nasz pan

**Comment by iti-tobiasz-gruszczynski** [comment]
Zadanie wykonane. Wątek zamknięty
