### ISSUE TITLE
Status UML

### ISSUE THREAD

**Issue by Szymon-Krysztopolski** [Gacioreks/ScenarioQualityChecker#2]

**Comment by Szymon-Krysztopolski** [comment]
@Gacioreks Krzychu pytanie do cb jak te Vizytejtory teraz działają? Bo je trzeba ładnie uwzględnić w UML'u 
@ reszta Ogólnie UML gotowy od dawna, ale z premierą czekamy do końca.

**Comment by iti-tobiasz-gruszczynski** [comment]
Pamiętajcie o wrzuceniu screena diagramu UML i zorganizowaniu URL

**Comment by Grabosk1** [comment]
UML gotowy, wystarczy wrzucić
