### ISSUE TITLE
Pliki JSON

### ISSUE THREAD

**Issue by iti-tobiasz-gruszczynski** [Gacioreks/ScenarioQualityChecker#8]
Wczytanie danych z pliku JSON. [V]
Dostosowanie wczytanych danych do metod. [V]
Zapisanie przetworzonych danych do pliku JSON. [X]

**Comment by Szymon-Krysztopolski** [comment]
Zapisuje obiekt do JSON'a 
Ogólnie działa dobrze, ale zostaje troche tych tymcasowych zmiennych typu list
nw czy to problem, ale naprawa tego może zając dużo cennego czasu

**Comment by Szymon-Krysztopolski** [comment]
if działa then go_next_task

**Comment by Szymon-Krysztopolski** [comment]
proponuje w niedalekiej przyszłości zrobić obiekt Scenario_export albo coś w tym stylu żeby przesyłać obiekt scenariusza bez naszych zmiennych pomocniczych

**Comment by iti-tobiasz-gruszczynski** [comment]
Obiekty zapisywane do formatu json i zwracane przez resta

**Comment by iti-tobiasz-gruszczynski** [comment]
Metody przetestowane. Działają poprawnie
